version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - WEBHOOK_URL=${WEBHOOK_URL}
    volumes:
      - ./api:/app
    env_file:
      - .env

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
